"""
    HomeWizard Energy API

    With the HomeWizard Energy platform, you can get insights in your energy usage. Use the HomeWizard Wi-Fi P1 meter to access real-time data directly from your smart meter, the HomeWizard Wi-Fi Energy Socket to get energy insights from all your devices, the HomeWizard Wi-Fi kWh meter to measure devices such as solar panels and the HomeWizard Wi-Fi Watermeter to get insight in your water usage. With the open API you can integrate the data directly into your system of choice.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import hwe
from hwe.api.homewizard_api import HomewizardApi  # noqa: E501


class TestHomewizardApi(unittest.TestCase):
    """HomewizardApi unit test stubs"""

    def setUp(self):
        self.api = HomewizardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_get(self):
        """Test case for api_get

        Basic information  # noqa: E501
        """
        pass

    def test_api_v1_data_get(self):
        """Test case for api_v1_data_get

        Recent measurement  # noqa: E501
        """
        pass

    def test_api_v1_state_get(self):
        """Test case for api_v1_state_get

        Actual State  # noqa: E501
        """
        pass

    def test_api_v1_telegram_get(self):
        """Test case for api_v1_telegram_get

        Recent telegram  # noqa: E501
        """
        pass

    def test_control_state(self):
        """Test case for control_state

        Control State  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
