"""
    HomeWizard Energy API

    With the HomeWizard Energy platform, you can get insights in your energy usage. Use the HomeWizard Wi-Fi P1 meter to access real-time data directly from your smart meter, the HomeWizard Wi-Fi Energy Socket to get energy insights from all your devices, the HomeWizard Wi-Fi kWh meter to measure devices such as solar panels and the HomeWizard Wi-Fi Watermeter to get insight in your water usage. With the open API you can integrate the data directly into your system of choice.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from hwe.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from hwe.exceptions import ApiAttributeError



class DataHweP1(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'smr_version': (float,),  # noqa: E501
            'meter_model': (str,),  # noqa: E501
            'wifi_ssid': (str,),  # noqa: E501
            'wifi_strength': (int,),  # noqa: E501
            'total_power_import_t1_kwh': (float,),  # noqa: E501
            'total_power_import_t2_kwh': (float,),  # noqa: E501
            'total_power_export_t1_kwh': (float,),  # noqa: E501
            'total_power_export_t2_kwh': (float,),  # noqa: E501
            'active_power_w': (float,),  # noqa: E501
            'active_power_l1_w': (float,),  # noqa: E501
            'active_power_l2_w': (float,),  # noqa: E501
            'active_power_l3_w': (float,),  # noqa: E501
            'total_gas_m3': (float, none_type,),  # noqa: E501
            'gas_timestamp': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'smr_version': 'smr_version',  # noqa: E501
        'meter_model': 'meter_model',  # noqa: E501
        'wifi_ssid': 'wifi_ssid',  # noqa: E501
        'wifi_strength': 'wifi_strength',  # noqa: E501
        'total_power_import_t1_kwh': 'total_power_import_t1_kwh',  # noqa: E501
        'total_power_import_t2_kwh': 'total_power_import_t2_kwh',  # noqa: E501
        'total_power_export_t1_kwh': 'total_power_export_t1_kwh',  # noqa: E501
        'total_power_export_t2_kwh': 'total_power_export_t2_kwh',  # noqa: E501
        'active_power_w': 'active_power_w',  # noqa: E501
        'active_power_l1_w': 'active_power_l1_w',  # noqa: E501
        'active_power_l2_w': 'active_power_l2_w',  # noqa: E501
        'active_power_l3_w': 'active_power_l3_w',  # noqa: E501
        'total_gas_m3': 'total_gas_m3',  # noqa: E501
        'gas_timestamp': 'gas_timestamp',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, smr_version, meter_model, wifi_ssid, wifi_strength, total_power_import_t1_kwh, total_power_import_t2_kwh, total_power_export_t1_kwh, total_power_export_t2_kwh, active_power_w, active_power_l1_w, *args, **kwargs):  # noqa: E501
        """DataHweP1 - a model defined in OpenAPI

        Args:
            smr_version (float):
            meter_model (str):
            wifi_ssid (str):
            wifi_strength (int):
            total_power_import_t1_kwh (float):
            total_power_import_t2_kwh (float):
            total_power_export_t1_kwh (float):
            total_power_export_t2_kwh (float):
            active_power_w (float):
            active_power_l1_w (float):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            active_power_l2_w (float): [optional]  # noqa: E501
            active_power_l3_w (float): [optional]  # noqa: E501
            total_gas_m3 (float, none_type): [optional]  # noqa: E501
            gas_timestamp (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.smr_version = smr_version
        self.meter_model = meter_model
        self.wifi_ssid = wifi_ssid
        self.wifi_strength = wifi_strength
        self.total_power_import_t1_kwh = total_power_import_t1_kwh
        self.total_power_import_t2_kwh = total_power_import_t2_kwh
        self.total_power_export_t1_kwh = total_power_export_t1_kwh
        self.total_power_export_t2_kwh = total_power_export_t2_kwh
        self.active_power_w = active_power_w
        self.active_power_l1_w = active_power_l1_w
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, smr_version, meter_model, wifi_ssid, wifi_strength, total_power_import_t1_kwh, total_power_import_t2_kwh, total_power_export_t1_kwh, total_power_export_t2_kwh, active_power_w, active_power_l1_w, *args, **kwargs):  # noqa: E501
        """DataHweP1 - a model defined in OpenAPI

        Args:
            smr_version (float):
            meter_model (str):
            wifi_ssid (str):
            wifi_strength (int):
            total_power_import_t1_kwh (float):
            total_power_import_t2_kwh (float):
            total_power_export_t1_kwh (float):
            total_power_export_t2_kwh (float):
            active_power_w (float):
            active_power_l1_w (float):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            active_power_l2_w (float): [optional]  # noqa: E501
            active_power_l3_w (float): [optional]  # noqa: E501
            total_gas_m3 (float, none_type): [optional]  # noqa: E501
            gas_timestamp (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.smr_version = smr_version
        self.meter_model = meter_model
        self.wifi_ssid = wifi_ssid
        self.wifi_strength = wifi_strength
        self.total_power_import_t1_kwh = total_power_import_t1_kwh
        self.total_power_import_t2_kwh = total_power_import_t2_kwh
        self.total_power_export_t1_kwh = total_power_export_t1_kwh
        self.total_power_export_t2_kwh = total_power_export_t2_kwh
        self.active_power_w = active_power_w
        self.active_power_l1_w = active_power_l1_w
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
