# flake8: noqa

"""
    HomeWizard Energy API

    With the HomeWizard Energy platform, you can get insights in your energy usage. Use the HomeWizard Wi-Fi P1 meter to access real-time data directly from your smart meter, the HomeWizard Wi-Fi Energy Socket to get energy insights from all your devices, the HomeWizard Wi-Fi kWh meter to measure devices such as solar panels and the HomeWizard Wi-Fi Watermeter to get insight in your water usage. With the open API you can integrate the data directly into your system of choice.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from hwe.api_client import ApiClient

# import Configuration
from hwe.configuration import Configuration

# import exceptions
from hwe.exceptions import OpenApiException
from hwe.exceptions import ApiAttributeError
from hwe.exceptions import ApiTypeError
from hwe.exceptions import ApiValueError
from hwe.exceptions import ApiKeyError
from hwe.exceptions import ApiException
